# this file contains make info needed by the Rules.mk of base and/or other projects; it cannot go in Rules.mk,
# which gets included in tree-traversal order (so a Rules.mk needed by a second Rules.mk might not yet
# be included)

# project name override
# PROJECT := ...

# project-specific installation dir override
# INCS_INSTALL_DIR_$(PROJECT) := ...
# LIBS_INSTALL_DIR_$(PROJECT) := ...
# BINS_INSTALL_DIR_$(PROJECT) := ...

