#! /bin/csh -f

# optional arg is start_time
# set echo

# make movie of last days days at cadence cadence
# choices if cadence must be multiple of 15m.
if ( ! $?WORKFLOW_IMG_ROOT ) then
    echo WORKFLOW_IMG_ROOT environment variable is undefined
    exit 1
endif

if (!(-e $WORKFLOW_IMG_ROOT)) then
    mkdir $WORKFLOW_IMG_ROOT
    if ($?) then 
        echo "[ makeIcmovie ] ERROR making image root directory $WORKFLOW_IMG_ROOT"
        exit 1
    endif
endif

set TIME_CONVERT = "${DRMS_BINS_INSTALL_DIR}"/time_convert

if ($#argv > 0) then
    set want = $1
    set want_t = `$TIME_CONVERT time=$want`
    @ wantimg = $want_t / 900
    @ endtime_t = $wantimg * 900
else
    set now = `date -u +%Y.%m.%d_%H:%M:%S`
    set now_t = `$TIME_CONVERT time=$now`
    @ nowimg = $now_t / 900
    @ nowimg_t = $nowimg * 900
    @ endtime_t = $nowimg_t - 3600
endif

set Type = jpg
set Size = 1k
set minFileSize = 50000

set images_dir = $WORKFLOW_IMG_ROOT/images
if (!(-e $images_dir)) then
    mkdir $images_dir
    if ($?) then 
        echo "[ makeIcmovie ] ERROR making images directory $images_dir"
        exit 1
    endif
endif

set movies_dir = $WORKFLOW_IMG_ROOT/movies
if (!(-e $movies_dir)) then
    mkdir $movies_dir
    if ($?) then 
        echo "[ makeIcmovie ] ERROR making movies directory $movies_dir"
        exit 1
    endif
endif

set latest_movies_dir = $movies_dir/latest
if (!(-e $latest_movies_dir)) then
    mkdir $latest_movies_dir
    if ($?) then 
        echo "[ makeIcmovie ] ERROR making latest movies directory $latest_movies_dir"
        exit 1
    endif
endif

set d14d_movies = $movies_dir/.14dmovies
if (!(-e $d14d_movies)) then
    mkdir $d14d_movies
    if ($?) then 
        echo "[ makeIcmovie ] ERROR making d14d movies directory $d14d_movies"
        exit 1
    endif
endif

foreach Quant (Ic_flat M M_color)
    set work_dir = $movies_dir/$Quant'_movies'.$$

    if (!(-e $work_dir)) then
        mkdir $work_dir
        if ($?) then 
            echo "[ makeIcmovie ] ERROR making work directory $work_dir"
            exit 1
        endif
    endif

    set frames_dir = $work_dir/frames
    if (!(-e $frames_dir)) then
        mkdir $frames_dir
        if ($?) then 
            echo "[ makeIcmovie ] ERROR making frames directory $frames_dir"
            exit 1
        endif
    endif

    # First make 2 days at 15 minutes
    @ imgtime_t = $endtime_t - 172800
    @ cadence = 15 * 60

    set i = 0
    while ($imgtime_t <= $endtime_t)
        set imgtime = `$TIME_CONVERT s=$imgtime_t zone=TAI`
        set yyyymmdd = `echo $imgtime | sed -e 's/_.*//' -e 's/\./Q/' -e 's/\./X/'`
        set YEAR = `echo $yyyymmdd | sed -e 's/Q.*//'`
        set MON = `echo $yyyymmdd | sed -e 's/^.*Q//' -e 's/X.*//'`
        set DAY = `echo $yyyymmdd | sed -e 's/^.*X//'`
        set yyyymmdd = $YEAR$MON$DAY
        set hhmmss = `echo $imgtime | sed -e 's/_/Q/' -e 's/.*Q//' -e 's/://g' -e 's/_TAI//'`
        set I = `printf "%04d" $i`
        set filename = $yyyymmdd'_'$hhmmss'_'$Quant'_'$Size'.'$Type
        set Imgpath = $images_dir/$YEAR/$MON/$DAY
        set targpath = $frames_dir
        set Image = $Imgpath/$filename

        if (-e $Image) then
            set FileSize=`stat --format="%s" $Image`
            if ($FileSize < $minFileSize) then
                echo Blank image detected for $Image
            else
                ln -s $Image $targpath/$I.$Type
                @ i = $i + 1
            endif
        else
            echo no frame found for $Image
        endif

        @ imgtime_t = $imgtime_t + $cadence
    end

    ls -ld $frames_dir
    cd $frames_dir

    echo Movie making place is $cwd

    if ( $JSOC_MACHINE == 'linux_avx' ) then
        set mpg_opts = "-b:v 35000k"
        #    set mp4_opts = "-qscale 5 -b 9600"
        set mp4_opts = "-b:v 35000k"
    else
        set mpg_opts = "-qscale 5 -r 20 -b 9600" 
        set mp4_opts = "-qscale 5 -r 20 -b 9600"
    endif

    set MOVIE = $work_dir/$Quant'_2d'.mpg
    #  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $MOVIE 
    ffmpeg -i %04d.$Type $mpg_opts $MOVIE

    # the cp commands use $Imgpath, which is not defined in this scope; it 
    # was defined in the above while loop, and it takes on a different value
    # during each iteration; the value used here will be either the last value
    # of the iteration, or I guess the empty string if the while loop above
    # never executed - THIS IS A BUG
    set image_dir = $Imgpath
    if (!(-e $image_dir)) then
        mkdir $image_dir
        if ($?) then 
            echo "[ makeIcmovie ] ERROR making image directory $image_dir"
            exit 1
        endif
    endif

    if ($status == 0) then
        cp $MOVIE $Imgpath
        mv $MOVIE $latest_movies_dir
    endif
  
    set MOVIE = $work_dir/$Quant'_2d'.mp4
    #  ffmpeg -qscale 5 -r 20 -b 9600 -i %04d.$Type $MOVIE
    ffmpeg -i %04d.$Type $mp4_opts $MOVIE

    if ($status == 0) then
        cp $MOVIE $Imgpath
        mv $MOVIE $latest_movies_dir
    endif

    cd $movies_dir

    # on even hour endtime, make longer movie also
    @ nowtime_t = $endtime_t / 3600
    @ nowhour_t = $nowtime_t * 3600
    if ($nowhour_t == $endtime_t) then
        cd $frames_dir
        @ fourteen = 86400 * 14
        @ nowtime_t = $endtime_t - $fourteen
        set nowtime = `$TIME_CONVERT zone=TAI s=$nowtime_t`
        set endtime = `$TIME_CONVERT zone=TAI s=$endtime_t`
        "${DRMS_SCRS_INSTALL_DIR}"/makeAnyMovie $nowtime $endtime 15 $Quant 1k ""$d14d_movies/$Quant"_14d.mp4"
    endif
end

ls -l $d14d_movies/
mv $d14d_movies/Ic_flat_14d.mp4 $d14d_movies/M_14d.mp4 $latest_movies_dir/
mv $d14d_movies/M_color_14d.mp4 $latest_movies_dir/
rm -rf $d14d_movies
rm -rf $movies_dir/*.$$
