#! /bin/csh -f
#

# Verify our workflow environment variables are set
# Assumes this script is run from the root of the workflow directory
set script_dir = `cd $(dirname $0) && pwd`
source "$script_dir/setup_workflow.csh"

set SHOW_INFO = "${DRMS_BINS_INSTALL_DIR}"/show_info
set TIME_CONVERT = "${DRMS_BINS_INSTALL_DIR}"/time_convert

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
  echo waiting for gatekeeper to quit.
  sleep 5
  end

# begin section for this product

# make test gates and tasks for HMI line-of-sight observables
# This includes the several input series.

# remove prior versions

cd $WORKFLOW_DATA/gates
rm -rf aia.lev1 aia.lev0

cd $WORKFLOW_DATA/tasks
rm -rf update_aia.lev1 stage_aia.lev0

# Make tasks and set preconditions

# NOTE the "command" script used below must be available and executable when this script is run
cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_aia.lev1 manager=taskmanager.csh target=aia.lev1 \
		command=scripts/update_aia.lev1.csh maxrange=86400 parallelOK=5

set PRECOND = $WORKFLOW_DATA/tasks/update_aia.lev1/preconditions

# Use action=5 since the action task for lev0 wants a big range and will only stage
# SUs that are offline.

mkdir $PRECOND/aia.lev0
cat > $PRECOND/aia.lev0/prepare_ticket <<STOP
    set ACTION = 5
    set prewanthigh_t = \`$TIME_CONVERT time=\$WANTHIGH\`
    set prewantlow_t =  \`$TIME_CONVERT time=\$WANTLOW\`
    set USELOW =  \`$SHOW_INFO -q key=FSN aia.lev0'[? T_OBS>='\$prewantlow_t' AND T_OBS<='\$prewanthigh_t' ?]' n=1\`
    set USEHIGH = \`$SHOW_INFO -q key=FSN aia.lev0'[? T_OBS>='\$prewantlow_t' AND T_OBS<='\$prewanthigh_t' ?]' n=-1\`
STOP

# Prerequisite task is aia.lev0

$WORKFLOW_DIR/maketask.csh task=stage_aia.lev0 manager=taskmanager.csh target=aia.lev0 \
		command=scripts/stage_lev0_by_FSN.csh maxrange=86400 parallelOK=1


# Now make gates.

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=aia.lev1 product=aia.lev1 type=time key=T_REC project=AIA \
		 actiontask=update_aia.lev1 statustask=scripts/status-general.csh

# Prerequisite gates

$WORKFLOW_DIR/makegate.csh gate_name=aia.lev0 product=aia.lev0 type=FSN key=FSN project=AIA \
		 actiontask=stage_aia.lev0 statustask=scripts/status_aia.lev0.csh coverage_args=NEVER

# initialize the gates
$SHOW_INFO key=FSN -q aia.lev0'[^]'                          > $WORKFLOW_DATA/gates/aia.lev0/low
$SHOW_INFO key=FSN -q aia.lev0'[? FSN<400000000 ?]' n=-1     > $WORKFLOW_DATA/gates/aia.lev0/high

$SHOW_INFO key=T_REC -q aia.lev1'[? T_REC_index > 0 ?]' n=1  > $WORKFLOW_DATA/gates/aia.lev1/low
$SHOW_INFO key=T_REC -q aia.lev1'[$]'                        > $WORKFLOW_DATA/gates/aia.lev1/high
