#! /bin/csh -f

#
# WARNING - do not run this while gatekeeper is active

# script to add a repeating processing to make e.g. to run a task each day.

# This script is setup for HMI LOS data.

# Verify our workflow environment variables are set
# Assumes this script is run from the root of the workflow directory
set script_dir = `cd $(dirname $0) && pwd`
source "$script_dir/setup_workflow.csh"

cd $WORKFLOW_DATA

set NEWTASK = repeat_hmi_daily
set NEWGATE = repeat_hmi_daily

# remove prior test version

if (-e tasks/$NEWTASK) rm -rf tasks/$NEWTASK
if (-e gates/$NEWGATE) rm -rf gates/$NEWGATE

# finally make task 
$WORKFLOW_DIR/maketask.csh task=$NEWTASK manager=taskmanager.csh target=$NEWGATE maxrange=86400 \
                command=scripts/start_hmi_daily.csh

mkdir $WORKFLOW_DATA/tasks/$NEWTASK/precondition/hmi.lev1_wait_FSN
cat >$WORKFLOW_DATA/tasks/$NEWTASK/preconditions/hmi.lev1_wait_FSN/prepare_ticket <<STOP
    set ACTION = 3
STOP

mkdir $WORKFLOW_DATA/tasks/$NEWTASK/preconditions/hmi.cosmic_rays
cat >$WORKFLOW_DATA/tasks/$NEWTASK/preconditions/hmi.cosmic_rays/prepare_ticket <<STOP
    set ACTION = 3
    set USEHIGH_t = \`time_convert time=\$USEHIGH\`
    @ USEHIGH_t = \$USEHIGH_t - 15
    set USEHIGH = \`time_convert s=\$USEHIGH_t zone=TAI\`
STOP


$WORKFLOW_DIR/makegate.csh gate_name=$NEWGATE product=none type=time key=NA \
	low=2010.03.24_00:00:00_TAI high=2010.03.24_00:00:00_TAI \
	actiontask=$NEWTASK statustask=scripts/status_clock.csh
# initialization ticket not needed. 
