#! /bin/csh -f
#
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

if ( ! $?WORKFLOW_DIR ) then
    echo WORKFLOW_DIR environment variable is undefined, setting local variable to "${DRMS_SRC_INSTALL_DIR}"/workflow
    set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow
endif

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

# begin section for this product

cd $WORKFLOW_DATA/gates
rm -rf hmi.Marmask

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.Marmask 

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.Marmask \
            manager=taskmanager.csh \
            target=hmi.Marmask \
            command=scripts/update_hmi.Marmask.csh \
            maxrange=86400 \
            parallelOK=20

set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.Marmask/preconditions

mkdir $PRECOND/hmi.Vector
cat > $PRECOND/hmi.Vector/prepare_ticket <<STOP
    set ACTION = 3
STOP

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.Marmask \
            product=hmi.Marmask_720s \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.Marmask \
            statustask=scripts/status-general.csh
