#! /bin/csh -f
#
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

# begin section for this product

cd $WORKFLOW_DATA/gates
rm -rf hmi.sharp

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.sharp

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.sharp manager=taskmanager.csh target=hmi.sharp \
            command=scripts/update_hmi.sharp.csh maxrange=86400 parallelOK=10

set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.sharp/preconditions

#mkdir $PRECOND/hmi.Vector
#cat > $PRECOND/hmi.Vector/prepare_ticket <<STOP
#    set ACTION = 3
#STOP

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.sharp product=hmi.sharp_720s type=time key=T_REC project=HMI \
            actiontask=update_hmi.sharp statustask=scripts/status-general.csh
