#! /bin/csh -f
#
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

# begin section for this product

# make test gates and tasks for HMI Vector_nrt Field and other 720s_nrt observables

# remove prior versions

cd $WORKFLOW_DATA/gates
rm -rf hmi.Vector_nrt 

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.Vector_nrt 

# Make tasks and set preconditions

# NOTE the "command" script used below must be available and executable when this script is run
cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.Vector_nrt \
            manager=taskmanager.csh \
            target=hmi.Vector_nrt \
            command=scripts/update_hmi.Vector_nrt.csh \
            maxrange=2160 \
            parallelOK=4

if ($status) exit 1

mkdir $WORKFLOW_DATA/tasks/update_hmi.Vector_nrt/preconditions/hmi.lev1_nrt
if ($status) exit 1
echo "set ACTION=3" > $WORKFLOW_DATA/tasks/update_hmi.Vector_nrt/preconditions/hmi.lev1_nrt/prepare_ticket

# NOTE hmi.S_720s_nrt is made at the same time as M, V, Ic, Ld, and Lw so only
# one product needs to be tracked here.

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.Vector_nrt \
            product=hmi.S_720s_nrt \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.Vector_nrt \
            statustask=scripts/status-general.csh
if ($status) exit 1

# Prerequisite gates made in LOS add script

# initialize the gates
$WORKFLOW_DIR/maketicket.csh gate=hmi.Vector_nrt wantlow=NaN wanthigh=NaN action=6
if ($status) exit 1

# RESTART gatekeeper

cd $WORKFLOW_DATA
$WORKFLOW_DIR/gatekeeper.csh >&log &
