#! /bin/csh -f
#
# these lines for all products
if ($?WORKFLOW_ROOT) then
  set WFDIR = $WORKFLOW_DATA
  set WFCODE = $WORKFLOW_ROOT
else
  echo Need WORKFLOW_ROOT variable to be set.
  exit 1
endif

cd $WFDIR
rm -f Keep_running
while (-e GATEKEEPERBUSY)
  echo waiting for gatekeeper to quit.
  sleep 5
  end

# begin section for this product

# make test gates and tasks for HMI Vector Field and other 720s observables
# This includes the several input series.

# remove prior versions

cd $WFDIR/gates
rm -rf hmi.VectorObsOnly 

cd $WFDIR/tasks
rm -rf update_hmi.VectorObsOnly 

# Make tasks and set preconditions

# NOTE the "command" script used below must be available and executable when this script is run
cd $WFDIR
$WFCODE/maketask.csh task=update_hmi.VectorObsOnly manager=taskmanager.csh target=hmi.VectorObsOnly \
		command=scripts/update_hmi.Vector_ObsOnly.csh maxrange=2160 parallelOK=5

# Now make any user gates.

# NOTE hmi.S_720s is made before  M, V, Ic, Ld, and Lw and they are made at one time so only
# one product needs to be tracked here.

cd $WFDIR
$WFCODE/makegate.csh gate_name=hmi.VectorObsOnly product=hmi.M_720s type=time key=T_REC project=HMI \
		 actiontask=update_hmi.VectorObsOnly statustask=scripts/status-general.csh

# Prerequisite gates made in LOS add script

# initialize the gates
$WFCODE/maketicket.csh gate=hmi.VectorObsOnly wantlow=NaN wanthigh=NaN action=6

