#! /bin/csh -f
#
# make test gates and tasks for HMI limb dark removed 12m data

# Verify our workflow environment variables are set
# Assumes this script is run from the root of the workflow directory
set script_dir = `cd $(dirname $0) && pwd`
source "$script_dir/setup_workflow.csh"

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
	echo waiting for gatekeeper to quit.
	sleep 5
end

cd $WORKFLOW_DATA/gates
rm -rf hmi.noLD_45_nrt

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.noLD_45_nrt

# Make task
cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.noLD_45_nrt \
            manager=taskmanager.csh \
            target=hmi.noLD_45_nrt \
            command=scripts/update_hmi.Ic_noLimbDark \
            maxrange=86400 \
            parallelOK=5
set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.noLD_45_nrt/preconditions/hmi.Vector
mkdir $PRECOND
echo "set ACTION = 3" > $PRECOND/prepare_ticket

# Now make gate.

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.noLD_45_nrt \
            product=hmi.Ic_noLimbDark_45s_nrt \
            type=time \
            key=T_REC \
            project=HMI \
            low=2011.03.24_TAI \
            high=2011.03.24_TAI \
            actiontask=update_hmi.noLD_45_nrt \
            statustask=scripts/status-general.csh
