#! /bin/csh -f
#

# Verify our workflow environment variables are set
# Assumes this script is run from the root of the workflow directory
set script_dir = `cd $(dirname $0) && pwd`
source "$script_dir/setup_workflow.csh"

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

# begin section for this product

cd $WORKFLOW_DATA/gates
rm -rf hmi.Marmask

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.Marmask 

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.Marmask \
            manager=taskmanager.csh \
            target=hmi.Marmask \
            command=scripts/update_hmi.Marmask.csh \
            maxrange=86400 \
            parallelOK=20

set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.Marmask/preconditions

mkdir $PRECOND/hmi.Vector
cat > $PRECOND/hmi.Vector/prepare_ticket <<STOP
    set ACTION = 3
STOP

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.Marmask \
            product=hmi.Marmask_720s \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.Marmask \
            statustask=scripts/status-general.csh
