#! /bin/csh -f
#
# WARNING - do not run this while gatekeeper is active
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow

# Remove prior tests
cd $WORKFLOW_DATA
if (-e tasks/update_mdi.vw_V) rm -rf tasks/update_mdi.vw_V tasks/stage_dsds.vw_V
if (-e gates/mdi.vwV) rm -rf gates/mdi.vwV gates/dsds.vwV

# Make tasks

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_mdi.vw_V \
            manager=taskmanager.csh \
            target=mdi.vwV \
            command=scripts/update-mdi.vw_V \
            maxrange=864000 \
            parallelOK=10
mkdir $WORKFLOW_DATA/tasks/update_mdi.vw_V/preconditions/dsds.vwV
echo "set ACTION = 5" > $WORKFLOW_DATA/tasks/update_mdi.vw_V/preconditions/dsds.vwV/prepare_ticket

# specific update task to stage hourly DSDS data, only the taskname and target need to be specific
$WORKFLOW_DIR/maketask.csh task=stage_dsds.vw_V \
            manager=taskmanager.csh \
            target=dsds.vwV \
            command=scripts/stage-dsds_sixhour_data.csh \
            maxrange=8640000

# Make gates
cd $WORKFLOW_DATA
# use type time and let the status and action tasks convert to DSDS seriesnumbers
$WORKFLOW_DIR/makegate.csh gate_name=mdi.vwV \
            product=mdi.vw_V_lev18 \
            type=time \
            key=T_REC \
            project=MDI \
            actiontask=update_mdi.vw_V \
            statustask=scripts/status-mdi.vw_V_lev18.csh



# gate for staging DSDS data, the gatename, product, and actiontask need to be specific
$WORKFLOW_DIR/makegate.csh gate_name=dsds.vwV \
            product=dsds.mdi__lev1_8__vw_V_06h \
            type=time \
            key=snum \
            project=MDI \
            actiontask=stage_dsds.vw_V \
            statustask=scripts/status-dsds_sixhour.csh

# Make initialization tickets
$WORKFLOW_DIR/maketicket.csh gate=mdi.vwV action=6 wantlow=NaN wanthigh=NaN
$WORKFLOW_DIR/maketicket.csh gate=dsds.vwV action=6 wantlow=NaN wanthigh=NaN
