#! /bin/csh -f
#
# make test gates and tasks for HMI line-of-sight NRT observables
if ( ! $?WORKFLOW_IMG_ROOT ) then
    echo WORKFLOW_IMG_ROOT environment variable is undefined
    exit 1
endif

if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow

# Stop the gatekeeper in case it is running.

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

cd $WORKFLOW_DATA/gates
rm -rf hmi.webImages

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.webImages

# Make supporting scripts

# cat > $WORKFLOW_DIR/scripts/update_hmi.webImages <<END
# #! /bin/csh -f
# set wantlow = \`cat wantlow\`
# set wanthigh = \`cat wanthigh\`
# $WORKFLOW_DIR/scripts/makeimageslowhigh \$wantlow \$wanthigh
# set stat = \$status
# exit \$stat
# END
# chmod +x  $WORKFLOW_DIR/scripts/update_hmi.webImages

# cat > $WORKFLOW_DIR/scripts/status_hmi.webImages <<END
# set low = 2010.02.11_00:00:00_TAI
# set IMGROOT = $WORKFLOW_IMG_ROOT/images
# set LATESTLIST = \$IMGROOT/image_times_UTC
# set prevd = 0
# set prevt = 0
# if (-e \$LATESTLIST) then
  # set prevM = \`grep M \$LATESTLIST\`
  # set prevdt = \$prevM[2]
  # set prevd = \`echo \$prevdt | sed -e 's/_.*//'\`
  # set prevt = \`echo \$prevdt | sed -e 's/.*_//'\`
  # set highdate = \`echo \$prevd | sed -e 's/..../&./' -e 's/......./&./'\`
  # set hightime = \`echo \$prevt | sed -e 's/../&:/' -e 's/...../&:/'\`
  # set high = \$highdate'_'\$hightime'_TAI'
# else
  # set high = \$low
# endif
# echo \$low >low
# echo \$high > high
# 
# set nowtxt = \`date -u +%Y.%m.%d_%H:%M:%S\`
# echo \$nowtxt > lastupdate
# 
# rm -f statusbusy
# END
# chmod +x $WORKFLOW_DIR/scripts/status_hmi.webImages

# Make task

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.webImages \
            manager=taskmanager.csh \
            target=hmi.webImages \
            command=scripts/update_hmi.webImages \
            maxrange=86400 \
            parallelOK=0
set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.webImages/preconditions/hmi.LOSnrt
mkdir $PRECOND
echo "set ACTION = 3" > $PRECOND/prepare_ticket

# Now make gate.

cd $WORKFLOW_DATA
# use type time and let the status and action tasks convert to DSDS seriesnumbers
$WORKFLOW_DIR/makegate.csh gate_name=hmi.webImages \
            product=hmi.M_45s_nrt \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.webImages \
            statustask=scripts/status_hmi.webImages
