#! /bin/csh -f
#
# these lines for all products
if ($?WORKFLOW_ROOT) then
  set WFDIR = $WORKFLOW_DATA
  set WFCODE = $WORKFLOW_ROOT
else
  echo Need WORKFLOW_ROOT variable to be set.
  exit 1
endif

cd $WFDIR
rm -f Keep_running
while (-e GATEKEEPERBUSY)
  echo waiting for gatekeeper to quit.
  sleep 5
  end

# begin section for this product

cd $WFDIR/gates
rm -rf hmi.sharp

cd $WFDIR/tasks
rm -rf update_hmi.sharp

cd $WFDIR
$WFCODE/maketask.csh task=update_hmi.sharp manager=taskmanager.csh target=hmi.sharp \
		command=scripts/update_hmi.sharp.csh maxrange=86400 parallelOK=10

set PRECOND = $WFDIR/tasks/update_hmi.sharp/preconditions

#mkdir $PRECOND/hmi.Vector
#cat > $PRECOND/hmi.Vector/prepare_ticket <<STOP
#    set ACTION = 3
#STOP

cd $WFDIR
$WFCODE/makegate.csh gate_name=hmi.sharp product=hmi.sharp_720s type=time key=T_REC project=HMI \
		 actiontask=update_hmi.sharp statustask=scripts/status-general.csh



