#! /bin/csh -f
#
# make test gates and tasks for HMI line-of-sight NRT observables

if ($?WORKFLOW_ROOT) then
  set WFDIR = $WORKFLOW_DATA
  set WFCODE = $WORKFLOW_ROOT
else
  echo Need WORKFLOW_ROOT variable to be set.
  exit 1
endif

# Stop the gatekeeper in case it is running.

cd $WFDIR
rm -f Keep_running
while (-e GATEKEEPERBUSY)
  echo waiting for gatekeeper to quit.
  sleep 5
  end

cd $WFDIR/gates
rm -rf hmi.webImages

cd $WFDIR/tasks
rm -rf update_hmi.webImages

# Make supporting scripts

# cat > $WFCODE/scripts/update_hmi.webImages <<END
# #! /bin/csh -f
# set wantlow = \`cat wantlow\`
# set wanthigh = \`cat wanthigh\`
# $WFCODE/scripts/makeimageslowhigh \$wantlow \$wanthigh
# set stat = \$status
# exit \$stat
# END
# chmod +x  $WFCODE/scripts/update_hmi.webImages

# cat > $WFCODE/scripts/status_hmi.webImages <<END
# set low = 2010.02.11_00:00:00_TAI
# set IMGROOT = /home/jsoc/hmi/images
# set LATESTLIST = \$IMGROOT/image_times_UTC
# set prevd = 0
# set prevt = 0
# if (-e \$LATESTLIST) then
  # set prevM = \`grep M \$LATESTLIST\`
  # set prevdt = \$prevM[2]
  # set prevd = \`echo \$prevdt | sed -e 's/_.*//'\`
  # set prevt = \`echo \$prevdt | sed -e 's/.*_//'\`
  # set highdate = \`echo \$prevd | sed -e 's/..../&./' -e 's/......./&./'\`
  # set hightime = \`echo \$prevt | sed -e 's/../&:/' -e 's/...../&:/'\`
  # set high = \$highdate'_'\$hightime'_TAI'
# else
  # set high = \$low
# endif
# echo \$low >low
# echo \$high > high
# 
# set nowtxt = \`date -u +%Y.%m.%d_%H:%M:%S\`
# echo \$nowtxt > lastupdate
# 
# rm -f statusbusy
# END
# chmod +x $WFCODE/scripts/status_hmi.webImages

# Make task

cd $WFDIR
$WFCODE/maketask.csh task=update_hmi.webImages \
		manager=taskmanager.csh \
		target=hmi.webImages \
		command=scripts/update_hmi.webImages \
		maxrange=86400 \
		parallelOK=0
set PRECOND = $WFDIR/tasks/update_hmi.webImages/preconditions/hmi.LOSnrt
mkdir $PRECOND
echo "set ACTION = 3" > $PRECOND/prepare_ticket

# Now make gate.

cd $WFDIR
# use type time and let the status and action tasks convert to DSDS seriesnumbers
$WFCODE/makegate.csh gate_name=hmi.webImages \
		 product=hmi.M_45s_nrt \
		 type=time \
		 key=T_REC \
		 project=HMI \
		 actiontask=update_hmi.webImages \
		 statustask=scripts/status_hmi.webImages


