#! /bin/csh -f
#

# Verify our workflow environment variables are set
# Assumes this script is run from the root of the workflow directory
set script_dir = `cd $(dirname $0) && pwd`
source "$script_dir/setup_workflow.csh"

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

# begin section for this product

cd $WORKFLOW_DATA/gates
rm -rf hmi.ME_720s_fd10_nrt

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.ME_720s_fd10_nrt

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.ME_720s_fd10_nrt \
            manager=taskmanager.csh \
            target=hmi.ME_720s_fd10_nrt \
            command=scripts/update_hmi.ME_720s_fd10_nrt.csh \
            maxrange=86400 \
            parallelOK=4


cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.ME_720s_fd10_nrt \
            product=hmi.ME_720s_fd10_nrt \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.ME_720s_fd10_nrt \
            statustask=scripts/status-general.csh
