#! /bin/csh -f

#
# WARNING - do not run this while gatekeeper is active if it is updating an existing gate/task pair

# script to add a repeating processing to make e.g. to run a task each day.
# When it starts it will send a restart ticket to be restarted a fixed time later.
# The statustask is basically a nop
# The actiontask has a precondition of the full range of times in the calling ticket.
# The precondition ticket is to the clock_gate with a wait until ready action == 3.
# The command script first sends a ticket to its own gate to create the next interval
# then it does the desired action, which may be a maketicket or any other shell command
# computing.  It waits for the processing to be done but not for the repeat ticket.

# the case here is used like cron

# Verify our workflow environment variables are set
# Assumes this script is run from the root of the workflow directory
set script_dir = `cd $(dirname $0) && pwd`
source "$script_dir/setup_workflow.csh"

cd $WORKFLOW_DATA

set NEWTASK = repeat_web_show_coverage_task
set NEWGATE = repeat_web_show_coverage
set COMMANDSCRIPT = scripts/repeat_web_show_coverage.csh

# remove prior test version

if (-e tasks/$NEWTASK) rm -rf tasks/$NEWTASK
if (-e gates/$NEWGATE) rm -rf gates/$NEWGATE

# Parameters to control repeat timing
# REPEAT is wait time for next run of command
# set REPEAT = 7200

# make the actiontask command that will start processing when current wait interval ends
# cat >$WORKFLOW_DIR/scripts/$COMMANDSCRIPT << ENDSCRIPT
# #! /bin/csh -f
# set NOW = \`date -u +%Y.%m.%d_%H:%M:%S\`
# set NOW_t = \`time_convert time=\$NOW\`
# @ NEXTWANTHIGH_t = \$NOW_t + $REPEAT 
# set NEXTWANTHIGH = \`time_convert s=\$NEXTWANTHIGH_t\`
# set NEXTWANTLOW = \$NOW
# $WORKFLOW_DIR/maketicket.csh gate=$NEWGATE wantlow=\$NEXTWANTLOW wanthigh=\$NEXTWANTHIGH action=5
# #
# # now do the desired command(s)
# /web/jsoc/htdocs/doc/data/hmi/coverage_tables/update_coverage
# # /web/jsoc/htdocs/doc/data/hmi_test/update_coverage
# /web/jsoc/htdocs/doc/data/aia/update_coverage
# # /web/jsoc/htdocs/doc/data/aia_test/update_coverage
# /web/jsoc/htdocs/doc/data/mdi/update_coverage
# exit 0
# ENDSCRIPT


# finally make task 
$WORKFLOW_DATA/maketask.csh task=$NEWTASK \
                manager=taskmanager.csh \
                target=$NEWGATE \
                maxrange=8640000 \
                command=$COMMANDSCRIPT

# set the precondition ticket to wait for the end of the current interval
mkdir tasks/$NEWTASK/preconditions/clock_gate
echo "set ACTION=3" >tasks/$NEWTASK/preconditions/clock_gate/prepare_ticket

$WORKFLOW_DIR/makegate.csh gate_name=$NEWGATE \
                product=none \
                type=time \
                key=NA \
                low=1993.01.01_00:00:00_TAI \
                high=1993.01.01_00:00:00_TAI \
                actiontask=$NEWTASK \
                statustask=$WORKFLOW_DIR/scripts/status_clock.csh
# initialization ticket not needed. 
