#! /bin/csh -f
#
# these lines for all products
if ($?WORKFLOW_ROOT) then
  set WFDIR = $WORKFLOW_DATA
  set WFCODE = $WORKFLOW_ROOT
else
  echo Need WORKFLOW_ROOT variable to be set.
  exit 1
endif

cd $WFDIR
rm -f Keep_running
while (-e GATEKEEPERBUSY)
  echo waiting for gatekeeper to quit.
  sleep 5
  end

# begin section for this product

cd $WFDIR/gates
rm -rf hmi.Harp_nrt

cd $WFDIR/tasks
rm -rf update_hmi.Harp_nrt 

cd $WFDIR
$WFCODE/maketask.csh task=update_hmi.Harp_nrt manager=taskmanager.csh target=hmi.Harp_nrt \
		command=scripts/update_hmi.Harp_nrt.csh maxrange=86400 parallelOK=5

set PRECOND = $WFDIR/tasks/update_hmi.Harp_nrt/preconditions

mkdir $PRECOND/hmi.Marmask_nrt
cat > $PRECOND/hmi.Marmask_nrt/prepare_ticket <<STOP
    set ACTION = 3
STOP

cd $WFDIR
$WFCODE/makegate.csh gate_name=hmi.Harp_nrt product=hmi.MHarp_720s_nrt type=time key=T_REC project=HMI \
		 actiontask=update_hmi.Harp_nrt statustask=scripts/status-general.csh



