#! /bin/csh -f
#
# WARNING - do not run this while gatekeeper is active

set echo

if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

if ( ! $?WORKFLOW_DIR ) then
    echo WORKFLOW_DIR environment variable is undefined, setting local variable to "${DRMS_SRC_INSTALL_DIR}"/workflow
    set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow
endif

# script to add an clock, a clock that keeps time.
cd $WORKFLOW_DATA

# remove prior test version
if (-e tasks/clock_task) rm -rf tasks/clock_task 
if (-e gates/clock_gate) rm -rf gates/clock_gate

# get current hour slot
set NOW = `date -u +%Y.%m.%d_%H:%M:%S`

# make clock status task
# this status task will set the high value of the oclock gate to the current time.
cat > $WORKFLOW_DIR/scripts/status_clock.csh << ENDSCRIPT
#! /bin/csh -f
# the clock status task simply reflects the current time

cd $WORKFLOW_DATA/gates/\$1
set NOW = \`date -u +%Y.%m.%d_%H:%M:%S\`
echo \$NOW > high
echo \$NOW > lastupdate
rm -f statusbusy
ENDSCRIPT

chmod +x $WORKFLOW_DIR/scripts/status_clock.csh

# make the clock task
$WORKFLOW_DIR/maketask.csh task=clock_task \
                manager=taskmanager.csh \
                target=clock_gate \
                maxrange=86400 \
                command=scripts/true.csh

# make the clock gate
#
# WARNING - updelta MUST be more than the gatekeeper basic loop time or the clock will never process
# new tickets!

$WORKFLOW_DIR/makegate.csh gate_name=clock_gate \
                product=none \
                type=time \
                key=NA \
                low=1993 \
                high=$NOW \
                updatedelta=15 \
                actiontask=clock_task \
                statustask=scripts/status_clock.csh

# initialization tickets not needed. 
$WORKFLOW_DIR/enablegate.csh clock_gate
