#! /bin/csh -f
#

# Verify our workflow environment variables are set
# Assumes this script is run from the root of the workflow directory
set script_dir = `cd $(dirname $0) && pwd`
source "$script_dir/setup_workflow.csh"

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

# begin section for this product

cd $WORKFLOW_DATA/gates
rm -rf hmi.sharp_nrt

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.sharp_nrt

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.sharp_nrt \
            manager=taskmanager.csh \
            target=hmi.sharp_nrt \
            command=scripts/update_hmi.sharp_nrt.csh \
            maxrange=86400 \
            parallelOK=10

set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.sharp_nrt/preconditions

#mkdir $PRECOND/hmi.Vector
#cat > $PRECOND/hmi.Vector/prepare_ticket <<STOP
#    set ACTION = 3
#STOP

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.sharp_nrt \
            product=hmi_test.sharp_nrt \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.sharp_nrt \
            statustask=scripts/status-general.csh
