#! /bin/csh -f
#
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

if ( ! $?WORKFLOW_DIR ) then
    echo WORKFLOW_DIR environment variable is undefined, setting local variable to "${DRMS_SRC_INSTALL_DIR}"/workflow
    set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow
endif

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

# begin section for this product

# make test gates and tasks for HMI Vector Field and other 720s observables
# This includes the several input series.

# remove prior versions

cd $WORKFLOW_DATA/gates
rm -rf hmi.VectorObsOnly 

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.VectorObsOnly 

# Make tasks and set preconditions

# NOTE the "command" script used below must be available and executable when this script is run
cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.VectorObsOnly \
            manager=taskmanager.csh \
            target=hmi.VectorObsOnly \
            command=scripts/update_hmi.Vector_ObsOnly.csh \
            maxrange=2160 \
            parallelOK=5

# Now make any user gates.

# NOTE hmi.S_720s is made before  M, V, Ic, Ld, and Lw and they are made at one time so only
# one product needs to be tracked here.

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.VectorObsOnly \
            product=hmi.M_720s \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.VectorObsOnly \
            statustask=scripts/status-general.csh

# Prerequisite gates made in LOS add script

# initialize the gates
$WORKFLOW_DIR/maketicket.csh gate=hmi.VectorObsOnly wantlow=NaN wanthigh=NaN action=6
