#! /bin/csh -f
#
# make test gates and tasks for HMI line-of-sight NRT observables
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow

# Stop the gatekeeper if it is running.
cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

cd $WORKFLOW_DATA/gates
rm -rf hmi.webFits_nrt

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.webFits_nrt

# Make supporting scripts

# $WORKFLOW_DIR/scripts/update_hmi.webFits_nrt made by hand

# Make task

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.webFits_nrt \
            manager=taskmanager.csh \
            target=hmi.webFits_nrt \
            command=scripts/update_hmi.webFits_nrt \
            maxrange=86400 \
            parallelOK=0
set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.webFits_nrt/preconditions/hmi.Vector_nrt
mkdir $PRECOND
echo "set ACTION = 3" > $PRECOND/prepare_ticket

# Now make gate.

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.webFits_nrt \
            product=su_phil.test1_resized \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.webFits_nrt \
            statustask=scripts/status-general.csh
