#! /bin/csh -f
#

# Verify our workflow environment variables are set
# Assumes this script is run from the root of the workflow directory
set script_dir = `cd $(dirname $0) && pwd`
source "$script_dir/setup_workflow.csh"

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

# begin section for this product

# make test gates and tasks for HMI limb_fit
# This includes the several input series.

# remove prior versions

cd $WORKFLOW_DATA/gates
rm -rf hmi.Limb_Fit

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.Limb_Fit

# Make tasks and set preconditions

# NOTE the "command" script used below must be available and executable when this script is run
cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.Limb_Fit \
            manager=taskmanager.csh \
            target=hmi.Limb_Fit \
            command=scripts/update_hmi.Limb_Fit.csh \
            maxrange=1440 \
            parallelOK=10


cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.Limb_Fit \
            product=hmi.Limbfit_set \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.Limb_Fit \
            statustask=scripts/status-general.csh

# initialize the gates
$WORKFLOW_DIR/maketicket.csh gate=hmi.Limb_Fit \
            wantlow=NaN \
            wanthigh=NaN \
            action=6
