#! /bin/csh -f
#
# make test gates and tasks for HMI line-of-sight NRT observables
# hmi.lev1nrt
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

if ( ! $?WORKFLOW_DIR ) then
    echo WORKFLOW_DIR environment variable is undefined, setting local variable to "${DRMS_SRC_INSTALL_DIR}"/workflow
    set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow
endif

# Stop the gatekeeper if it is running.
cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

cd $WORKFLOW_DATA/gates
rm -rf hmi.lev1nrt

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.lev1nrt

# Make update script

# set SCRIPT = $WORKFLOW_DIR/scripts/update_hmi.lev1nrt.csh
# echo "#! /bin/csh -f" >$SCRIPT
# echo "# do nothing for now" >>$SCRIPT
# echo "exit 0" >>$SCRIPT
# chmod +x $SCRIPT

# Make any user tasks

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.lev1nrt \
            manager=taskmanager.csh \
            target=hmi.lev1nrt \
            command=scripts/update_hmi.lev1nrt.csh \
            maxrange=3600 \
            parallelOK=5

# Now make any user gates.

cd $WORKFLOW_DATA
# use type time and let the status and action tasks convert to DSDS seriesnumbers
$WORKFLOW_DIR/makegate.csh gate_name=hmi.lev1nrt \
            product=hmi.lev1_nrt \
            type=time \
            key=T_OBS \
            project=HMI \
            updatedelta=90 \
            actiontask=update_hmi.lev1nrt \
            statustask=scripts/status-general.csh

cd $WORKFLOW_DATA/gates/hmi.lev1nrt
echo 2010.04.24_TAI >low

# Now, to get things started, initialize the new gates.  this is not strictly necessary if the nextupdate
# times are defaulted to now.
