#! /bin/csh -f
#
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

if ( ! $?WORKFLOW_DIR ) then
    echo WORKFLOW_DIR environment variable is undefined, setting local variable to "${DRMS_SRC_INSTALL_DIR}"/workflow
    set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow
endif


cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
  echo waiting for gatekeeper to quit.
  sleep 5
  end

# begin section for this product

cd $WORKFLOW_DATA/gates
rm -rf hmi.Harp_nrt

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.Harp_nrt 

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.Harp_nrt manager=taskmanager.csh target=hmi.Harp_nrt \
            command=scripts/update_hmi.Harp_nrt.csh maxrange=86400 parallelOK=5

set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.Harp_nrt/preconditions

mkdir $PRECOND/hmi.Marmask_nrt
cat > $PRECOND/hmi.Marmask_nrt/prepare_ticket <<STOP
    set ACTION = 3
STOP

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.Harp_nrt product=hmi.MHarp_720s_nrt type=time key=T_REC project=HMI \
            actiontask=update_hmi.Harp_nrt statustask=scripts/status-general.csh
