#! /bin/csh -f
#
# these lines for all products
if ($?WORKFLOW_ROOT) then
  set WFDIR = $WORKFLOW_DATA
  set WFCODE = $WORKFLOW_ROOT
else
  echo Need WORKFLOW_ROOT variable to be set.
  exit 1
endif

cd $WFDIR
rm -f Keep_running
while (-e GATEKEEPERBUSY)
  echo waiting for gatekeeper to quit.
  sleep 5
  end

# begin section for this product

cd $WFDIR/gates
rm -rf hmi.ME_720s_fd10_nrt

cd $WFDIR/tasks
rm -rf update_hmi.ME_720s_fd10_nrt

cd $WFDIR
$WFCODE/maketask.csh task=update_hmi.ME_720s_fd10_nrt manager=taskmanager.csh target=hmi.ME_720s_fd10_nrt \
		command=scripts/update_hmi.ME_720s_fd10_nrt.csh maxrange=86400 parallelOK=4


cd $WFDIR
$WFCODE/makegate.csh gate_name=hmi.ME_720s_fd10_nrt product=hmi.ME_720s_fd10_nrt type=time key=T_REC project=HMI \
		 actiontask=update_hmi.ME_720s_fd10_nrt statustask=scripts/status-general.csh



