#! /bin/csh -f
#
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow

cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

# begin section for this product

cd $WORKFLOW_DATA/gates
rm -rf hmi.VFISV

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.VFISV

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.VFISV manager=taskmanager.csh target=hmi.VFISV \
            command=scripts/update_hmi.VFISV.csh maxrange=86400 parallelOK=10

set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.VFISV/preconditions

mkdir $PRECOND/hmi.Vector
cat > $PRECOND/hmi.Vector/prepare_ticket <<STOP
    set ACTION = 3
STOP

cd $WORKFLOW_DATA
$WORKFLOW_DIR/makegate.csh gate_name=hmi.VFISV product=hmi.ME_720s_fd10 type=time key=T_REC project=HMI \
            actiontask=update_hmi.VFISV.csh statustask=scripts/status-general.csh
