#! /bin/csh -f

#
# WARNING - do not run this while gatekeeper is active

# Verify our workflow environment variables are set
# Assumes this script is run from the root of the workflow directory
set script_dir = `cd $(dirname $0) && pwd`
source "$script_dir/setup_workflow.csh"

cd $WORKFLOW_DATA

set NEWTASK = update_hmi.harp_nrt
set NEWGATE = repeat_harp_nrt

# remove prior test version

if (-e tasks/$NEWTASK) rm -rf tasks/$NEWTASK
if (-e gates/$NEWGATE) rm -rf gates/$NEWGATE

# finally make task 
$WORKFLOW_DIR/maketask.csh task=$NEWTASK \
            manager=taskmanager.csh \
            target=$NEWGATE \
            maxrange=720 \
            command=scripts/start_hmi_harp_nrt.csh


$WORKFLOW_DIR/makegate.csh gate_name=$NEWGATE \
            product=none \
            type=time \
            key=NA \
            low=2010.03.24_00:00:00_TAI \
            high=2010.03.24_00:00:00_TAI \
            actiontask=$NEWTASK \
            statustask=scripts/status_clock.csh
# initialization ticket not needed. 
