#! /bin/csh -f
#
# make test gates and tasks for HMI Vector NRT observables

if ($?WORKFLOW_ROOT) then
  set WFDIR = $WORKFLOW_DATA
  set WFCODE = $WORKFLOW_ROOT
else
  echo Need WORKFLOW_ROOT variable to be set.
  exit 1
endif

# Stop the gatekeeper in case it is running.

cd $WFDIR
rm -f Keep_running
while (-e GATEKEEPERBUSY)
  echo waiting for gatekeeper to quit.
  sleep 5
  end

cd $WFDIR/gates
rm -rf hmi.Vectornrt

cd $WFDIR/tasks
rm -rf update_hmi.Vector_nrt

# Make any user tasks

cd $WFDIR
$WFCODE/maketask.csh task=update_hmi.Vector_nrt \
		manager=taskmanager.csh \
		target=hmi.Vector_nrt \
		command=scripts/update_hmi.Vector_nrt \
		maxrange=1200 \
		parallelOK=5
set PRECOND = $WFDIR/tasks/update_hmi.Vector_nrt/preconditions/hmi.lev1nrt
mkdir $PRECOND
echo "set ACTION = 3" > $PRECOND/prepare_ticket

# Now make any user gates.

cd $WFDIR
# use type time and let the status and action tasks convert to DSDS seriesnumbers
$WFCODE/makegate.csh gate_name=hmi.Vector_nrt \
		 product=hmi.M_720s_nrt \
		 type=time \
		 key=T_REC \
		 project=HMI \
		 actiontask=update_hmi.Vector_nrt \
		 statustask=scripts/status-general.csh

$WFCODE/maketicket.csh gate=hmi.Vector_nrt wantlow=NaN wanthigh=NaN action=6

