#! /bin/csh -f
#
# WARNING - do not run this while gatekeeper is active

set WFDIR = $WORKFLOW_DATA
set WFCODE = $WORKFLOW_ROOT

# Remove prior tests
cd $WFDIR
if (-e tasks/update_mdi.vw_V) rm -rf tasks/update_mdi.vw_V tasks/stage_dsds.vw_V
if (-e gates/mdi.vwV) rm -rf gates/mdi.vwV gates/dsds.vwV

# Make tasks

cd $WFDIR
$WFCODE/maketask.csh task=update_mdi.vw_V \
		manager=taskmanager.csh \
		target=mdi.vwV \
		command=scripts/update-mdi.vw_V \
		maxrange=864000 \
		parallelOK=10
mkdir tasks/update_mdi.vw_V/preconditions/dsds.vwV
echo "set ACTION = 5" > tasks/update_mdi.vw_V/preconditions/dsds.vwV/prepare_ticket

# specific update task to stage hourly DSDS data, only the taskname and target need to be specific
$WFCODE/maketask.csh task=stage_dsds.vw_V \
                manager=taskmanager.csh \
                target=dsds.vwV \
                command=scripts/stage-dsds_sixhour_data.csh \
                maxrange=8640000


# Make gates

cd $WFDIR
# use type time and let the status and action tasks convert to DSDS seriesnumbers
$WFCODE/makegate.csh gate_name=mdi.vwV \
		 product=mdi.vw_V_lev18 \
		 type=time \
		 key=T_REC \
		 project=MDI \
		 actiontask=update_mdi.vw_V \
		 statustask=scripts/status-mdi.vw_V_lev18.csh



# gate for staging DSDS data, the gatename, product, and actiontask need to be specific
$WFCODE/makegate.csh gate_name=dsds.vwV \
                 product=dsds.mdi__lev1_8__vw_V_06h \
                 type=time \
                 key=snum \
		 project=MDI \
                 actiontask=stage_dsds.vw_V \
                 statustask=scripts/status-dsds_sixhour.csh

# Make initialization tickets

$WFCODE/maketicket.csh gate=mdi.vwV action=6 wantlow=NaN wanthigh=NaN
$WFCODE/maketicket.csh gate=dsds.vwV action=6 wantlow=NaN wanthigh=NaN


