#! /bin/csh -f
#
# make test gates and tasks for HMI line-of-sight NRT observables
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

if ( ! $?WORKFLOW_DIR ) then
    echo WORKFLOW_DIR environment variable is undefined, setting local variable to "${DRMS_SRC_INSTALL_DIR}"/workflow
    set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow
endif

# Stop the gatekeeper if it is running.
cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

cd $WORKFLOW_DATA/gates
rm -rf hmi.LOSnrt

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.LOSnrt

# Make any user tasks

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.LOSnrt \
            manager=taskmanager.csh \
            target=hmi.LOSnrt \
            command=scripts/update_hmi.LOSnrt \
            maxrange=1200 \
            parallelOK=5

set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.LOSnrt/preconditions/hmi.lev1nrt
mkdir $PRECOND
echo "set ACTION = 3" > $PRECOND/prepare_ticket

# Now make any user gates.

cd $WORKFLOW_DATA
# use type time and let the status and action tasks convert to DSDS seriesnumbers
$WORKFLOW_DIR/makegate.csh gate_name=hmi.LOSnrt \
            product=hmi.M_45s_nrt \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.LOSnrt \
            statustask=scripts/status-general.csh

$WORKFLOW_DIR/maketicket.csh gate=hmi.LOSnrt wantlow=NaN wanthigh=NaN action=6
