#! /bin/csh -f
#
# make test gates and tasks for HMI Vector NRT observables
if ( ! $?WORKFLOW_DATA ) then
    echo WORKFLOW_DATA environment variable is undefined
    exit 1
endif

set WORKFLOW_DIR = "${DRMS_SRC_INSTALL_DIR}"/workflow

# Stop the gatekeeper if it is running.
cd $WORKFLOW_DATA
rm -f Keep_running
while (-e GATEKEEPERBUSY)
    echo waiting for gatekeeper to quit.
    sleep 5
end

cd $WORKFLOW_DATA/gates
rm -rf hmi.Vectornrt

cd $WORKFLOW_DATA/tasks
rm -rf update_hmi.Vector_nrt

# Make any user tasks

cd $WORKFLOW_DATA
$WORKFLOW_DIR/maketask.csh task=update_hmi.Vector_nrt \
            manager=taskmanager.csh \
            target=hmi.Vector_nrt \
            command=scripts/update_hmi.Vector_nrt \
            maxrange=1200 \
            parallelOK=5

set PRECOND = $WORKFLOW_DATA/tasks/update_hmi.Vector_nrt/preconditions/hmi.lev1nrt
mkdir $PRECOND
echo "set ACTION = 3" > $PRECOND/prepare_ticket

# Now make any user gates.

cd $WORKFLOW_DATA
# use type time and let the status and action tasks convert to DSDS seriesnumbers
$WORKFLOW_DIR/makegate.csh gate_name=hmi.Vector_nrt \
            product=hmi.M_720s_nrt \
            type=time \
            key=T_REC \
            project=HMI \
            actiontask=update_hmi.Vector_nrt \
statustask=scripts/status-general.csh

$WORKFLOW_DIR/maketicket.csh gate=hmi.Vector_nrt wantlow=NaN wanthigh=NaN action=6
